In [1]:
import torch
from torch import nn 
from torch import optim
from torch.autograd import Variable

In [2]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("Количество измерений:\n%s\n" % tensor.dim())
    print("Размер : ",  tensor.size())
    print("Тип : %s\n" % (tensor.type()))

In [3]:
# Создайте случайный FloatTensor размера 3x4x5

float_x = torch.randn([3, 4, 5], dtype=torch.float32)
print_tens_info(float_x)

X :
tensor([[[-1.4696,  0.4056,  1.6710, -1.1798,  0.6844],
         [-1.1954, -0.9837, -1.3403, -0.2635, -0.5861],
         [-1.3834, -0.0852,  0.1231, -0.5423, -0.3684],
         [ 0.6454,  0.3011,  0.9339,  2.4342, -0.0698]],

        [[-0.2386, -1.6714,  0.2958,  0.1874,  1.5840],
         [-0.1105, -1.3327, -1.1978, -0.3258, -1.0520],
         [ 0.5961,  0.1744,  1.4077, -0.1485,  0.6274],
         [-1.1666,  0.5265, -0.5704,  0.3126, -0.4520]],

        [[-0.9261,  0.4658,  1.2665, -0.4470, -0.4515],
         [-0.4956, -0.6534,  0.6143,  1.5877, -0.8341],
         [-1.1421,  1.1340, -0.9170, -0.4177,  0.9509],
         [ 0.1847,  1.5190,  0.8197, -0.7432, -1.2242]]])

Количество измерений:
3

Размер :  torch.Size([3, 4, 5])
Тип : torch.FloatTensor



In [4]:
# Выведите его форму (shape)

float_x.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6 X 10

print_tens_info(float_x.view(6,10))
float_x_reshape = float_x.view(6,10)
float_x_reshape

X :
tensor([[-1.4696,  0.4056,  1.6710, -1.1798,  0.6844, -1.1954, -0.9837, -1.3403,
         -0.2635, -0.5861],
        [-1.3834, -0.0852,  0.1231, -0.5423, -0.3684,  0.6454,  0.3011,  0.9339,
          2.4342, -0.0698],
        [-0.2386, -1.6714,  0.2958,  0.1874,  1.5840, -0.1105, -1.3327, -1.1978,
         -0.3258, -1.0520],
        [ 0.5961,  0.1744,  1.4077, -0.1485,  0.6274, -1.1666,  0.5265, -0.5704,
          0.3126, -0.4520],
        [-0.9261,  0.4658,  1.2665, -0.4470, -0.4515, -0.4956, -0.6534,  0.6143,
          1.5877, -0.8341],
        [-1.1421,  1.1340, -0.9170, -0.4177,  0.9509,  0.1847,  1.5190,  0.8197,
         -0.7432, -1.2242]])

Количество измерений:
2

Размер :  torch.Size([6, 10])
Тип : torch.FloatTensor



tensor([[-1.4696,  0.4056,  1.6710, -1.1798,  0.6844, -1.1954, -0.9837, -1.3403,
         -0.2635, -0.5861],
        [-1.3834, -0.0852,  0.1231, -0.5423, -0.3684,  0.6454,  0.3011,  0.9339,
          2.4342, -0.0698],
        [-0.2386, -1.6714,  0.2958,  0.1874,  1.5840, -0.1105, -1.3327, -1.1978,
         -0.3258, -1.0520],
        [ 0.5961,  0.1744,  1.4077, -0.1485,  0.6274, -1.1666,  0.5265, -0.5704,
          0.3126, -0.4520],
        [-0.9261,  0.4658,  1.2665, -0.4470, -0.4515, -0.4956, -0.6534,  0.6143,
          1.5877, -0.8341],
        [-1.1421,  1.1340, -0.9170, -0.4177,  0.9509,  0.1847,  1.5190,  0.8197,
         -0.7432, -1.2242]])

In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

y =  [1, 4, 2, 2, 1]
tensor2 = torch.FloatTensor(y)
float_x*tensor2

tensor([[[-1.4696,  1.6225,  3.3421, -2.3595,  0.6844],
         [-1.1954, -3.9348, -2.6807, -0.5270, -0.5861],
         [-1.3834, -0.3409,  0.2461, -1.0847, -0.3684],
         [ 0.6454,  1.2043,  1.8677,  4.8683, -0.0698]],

        [[-0.2386, -6.6856,  0.5916,  0.3748,  1.5840],
         [-0.1105, -5.3309, -2.3957, -0.6515, -1.0520],
         [ 0.5961,  0.6977,  2.8155, -0.2970,  0.6274],
         [-1.1666,  2.1060, -1.1408,  0.6252, -0.4520]],

        [[-0.9261,  1.8631,  2.5331, -0.8940, -0.4515],
         [-0.4956, -2.6136,  1.2287,  3.1754, -0.8341],
         [-1.1421,  4.5361, -1.8341, -0.8353,  0.9509],
         [ 0.1847,  6.0762,  1.6395, -1.4864, -1.2242]]])

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6


print_tens_info(torch.matmul(float_x_reshape, float_x_reshape.T))
torch.matmul(float_x_reshape, float_x_reshape.T)

X :
tensor([[11.5831, -0.3280,  4.7809,  3.9753,  4.3671, -0.1507],
        [-0.3280,  9.6752, -2.4870, -1.1514,  5.7861,  0.8651],
        [ 4.7809, -2.4870,  9.9181,  1.4326, -0.4320, -1.9631],
        [ 3.9753, -1.1514,  1.4326,  5.0486,  1.8523, -0.6777],
        [ 4.3671,  5.7861, -0.4320,  1.8523,  7.3488, -0.5575],
        [-0.1507,  0.8651, -1.9631, -0.6777, -0.5575,  9.5747]])

Количество измерений:
2

Размер :  torch.Size([6, 6])
Тип : torch.FloatTensor



tensor([[11.5831, -0.3280,  4.7809,  3.9753,  4.3671, -0.1507],
        [-0.3280,  9.6752, -2.4870, -1.1514,  5.7861,  0.8651],
        [ 4.7809, -2.4870,  9.9181,  1.4326, -0.4320, -1.9631],
        [ 3.9753, -1.1514,  1.4326,  5.0486,  1.8523, -0.6777],
        [ 4.3671,  5.7861, -0.4320,  1.8523,  7.3488, -0.5575],
        [-0.1507,  0.8651, -1.9631, -0.6777, -0.5575,  9.5747]])

In [9]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

def get_derivative_func(coordinates:list = [1, 0.5, 2]):
    """производные функции y = x**3 + z - 75t в точке (1, 0.5, 2)
    вывод: [производная по x, z, t]"""
    
    x = Variable(torch.ones(1)*coordinates[0], requires_grad = True)
    z = Variable(torch.ones(1)*coordinates[1], requires_grad = True)
    t = Variable(torch.ones(1)*coordinates[2], requires_grad = True)

    y = x**3 + z - 75*t
    y.backward(torch.ones(1))
    
    print(f'x.grad: {x.grad}\nz.grad: {z.grad}\nt.grad: {t.grad}\n')

In [10]:
print(3*1**2)
get_derivative_func()

3
x.grad: tensor([3.])
z.grad: tensor([1.])
t.grad: tensor([-75.])



In [11]:
print(3*2**2)
get_derivative_func(coordinates=[2, 67, 98])

12
x.grad: tensor([12.])
z.grad: tensor([1.])
t.grad: tensor([-75.])



In [12]:
print(3*6**2)
get_derivative_func(coordinates=[6, 67, 98])

108
x.grad: tensor([108.])
z.grad: tensor([1.])
t.grad: tensor([-75.])



In [13]:
# Создайте единичный тензор размера 5x6

z = torch.ones(5,6)
z

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [14]:
# Переведите его в формат numpy

z.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [15]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

def get_optimization_func(coordinat_x=1):
    """y = x**w - 2*x**2 + 5 in coordinat_x"""
    x = torch.ones(1)*coordinat_x
    w = Variable(torch.ones(1), requires_grad = True)

    optimizer = optim.SGD([w], lr=0.01)
    criterion = nn.MSELoss()
    optimizer.zero_grad()

    y = x**w - 2*x**2 + 5
    loss = criterion(y, torch.ones(1)*10)
    print(f"loss:\n\t{loss.item()}")
    loss.backward()
    optimizer.step()
    print(f"y = x**w - 2*x**2 + 5:\n\t{y}")
    print(f"w.grad:\n\t{w.grad}")

In [16]:
for coordiant in range(10):
    get_optimization_func(coordinat_x=coordiant)
    print('=='*33)

loss:
	25.0
y = x**w - 2*x**2 + 5:
	tensor([5.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-0.])
loss:
	36.0
y = x**w - 2*x**2 + 5:
	tensor([4.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-0.])
loss:
	121.0
y = x**w - 2*x**2 + 5:
	tensor([-1.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-30.4985])
loss:
	400.0
y = x**w - 2*x**2 + 5:
	tensor([-10.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-131.8335])
loss:
	1089.0
y = x**w - 2*x**2 + 5:
	tensor([-23.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-365.9817])
loss:
	2500.0
y = x**w - 2*x**2 + 5:
	tensor([-40.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-804.7190])
loss:
	5041.0
y = x**w - 2*x**2 + 5:
	tensor([-61.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-1526.5791])
loss:
	9216.0
y = x**w - 2*x**2 + 5:
	tensor([-86.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-2615.3032])
loss:
	15625.0
y = x**w - 2*x**2 + 5:
	tensor([-115.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-4158.8833])
loss:
	24964.0
y = x**w - 2*x**2 + 5:
	tensor([-148.], grad_fn=<A